import * as ExcelJS from 'exceljs';
import { logger } from './logger';

interface TimesheetReportData {
    entries: any[];
    filters: {
        employeeName?: string;
        projectName?: string;
        moduleName?: string;
        taskName?: string;

        startDate?: string;
        endDate?: string;
    };
    generatedBy: string;
    generatedAt: string;
}

export const generateTimesheetExcel = async (data: TimesheetReportData): Promise<Buffer> => {
    try {
        const workbook = new ExcelJS.Workbook();
        const worksheet = workbook.addWorksheet('Timesheet Report');

        // Styles
        const headerStyle: Partial<ExcelJS.Style> = {
            font: { bold: true, size: 12 },
            alignment: { vertical: 'middle', horizontal: 'center' },
            fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0E0E0' } }
        };

        const titleStyle: Partial<ExcelJS.Style> = {
            font: { bold: true, size: 16 },
            alignment: { horizontal: 'center' }
        };

        // Title
        worksheet.mergeCells('A1:H1');
        const titleCell = worksheet.getCell('A1');
        titleCell.value = 'Timesheet Report';
        titleCell.style = titleStyle;

        // Meta Info (Generated By, Date)
        worksheet.mergeCells('A2:D2');
        worksheet.getCell('A2').value = `Generated By: ${data.generatedBy}`;
        worksheet.mergeCells('E2:H2');
        worksheet.getCell('E2').value = `Generated At: ${new Date(data.generatedAt).toLocaleString()}`;
        worksheet.getCell('E2').alignment = { horizontal: 'right' };

        // Filters
        let currentRow = 4;
        const filterLabels = [
            { label: 'Employee', value: data.filters.employeeName },
            { label: 'Project', value: data.filters.projectName },
            { label: 'Module', value: data.filters.moduleName },
            { label: 'Task', value: data.filters.taskName },

            { label: 'Duration', value: `${data.filters.startDate || 'N/A'} to ${data.filters.endDate || 'N/A'}` }
        ];

        filterLabels.forEach(f => {
            if (f.value) {
                worksheet.getCell(`A${currentRow}`).value = f.label;
                worksheet.getCell(`A${currentRow}`).font = { bold: true };
                worksheet.getCell(`B${currentRow}`).value = f.value;
                currentRow++;
            }
        });

        currentRow++; // Gap before data

        // Header Row
        const headers = [
            'Date',
            'Employee',
            'Project',
            'Module',
            'Task',
            'Duration (Hrs)',
            'Status',
            'Description'
        ];

        const headerRow = worksheet.getRow(currentRow);
        headerRow.values = headers;
        headerRow.eachCell((cell: ExcelJS.Cell) => {
            cell.style = headerStyle;
            cell.border = {
                top: { style: 'thin' },
                left: { style: 'thin' },
                bottom: { style: 'thin' },
                right: { style: 'thin' }
            };
        });

        // Data Rows
        data.entries.forEach((entry, index) => {
            const row = worksheet.addRow([
                entry.log_date ? new Date(entry.log_date).toLocaleDateString() : 'N/A',
                entry.employee_name || 'N/A',
                entry.project_name || 'N/A',
                entry.module_name || 'N/A',
                entry.task_name || 'N/A',

                entry.duration || 0,
                entry.work_status || 'N/A',
                entry.description || ''
            ]);

            row.eachCell((cell: ExcelJS.Cell) => {
                cell.border = {
                    top: { style: 'thin' },
                    left: { style: 'thin' },
                    bottom: { style: 'thin' },
                    right: { style: 'thin' }
                };
                cell.alignment = { vertical: 'middle', wrapText: true };
            });
        });

        // Column Widths
        worksheet.columns = [
            { width: 15 }, // Date
            { width: 20 }, // Employee
            { width: 25 }, // Project
            { width: 25 }, // Module
            { width: 25 }, // Task

            { width: 15 }, // Duration
            { width: 15 }, // Status
            { width: 50 }  // Description
        ];

        const buffer = await workbook.xlsx.writeBuffer();
        return Buffer.from(buffer);
    } catch (error) {
        logger.error('[ExcelGenerator] Error generating Excel:', error);
        throw error;
    }
};
